package ca.utoronto.megaapp.ui.util

val migrationMap = mapOf(
    "portal" to "portal",
    "library" to "library",
    "newsuoft" to "newsuoft",
    "newsutm" to "newsutm",
    "newsutsc" to "newsutsc",
    "newsfas" to "newsartssci",
    "newsengi" to "newseng",
    "events" to "events",
    "dates" to "dates",
    "uoftmag" to "uoftmagazine",
    "edgemag" to "edgemagazine",
    "presidentblog" to "presblogs",
    "gradlifeblog" to "gradlifeblogs",
    "ulife" to "ulife",
    "varsityblues" to "blues",
    "maps" to "maps",
    "tours" to "tours",
    "systemstatus" to "SystemStatus",
    "email" to "email",
    "facebookuoft" to "facebookuoft",
    "twitteruoft" to "twitteruoft",
    "youtubeuoft" to "youtubeuoft",
    "facebookutm" to "facebookutm",
    "twitterutm" to "twitterutm",
    "youtubeutm" to "youtubeutm",
    "facebookutsc" to "facebookutsc",
    "twitterutsc" to "twitterutsc",
    "youtubeutsc" to "youtubeutsc",
    "linkedinuoft" to "linkedinuoft",
    "instagramuoft" to "instagramuoft",
    "instagrameng" to "instagrameng",
    "facebookeng" to "facebookeng",
    "twittereng" to "twittereng",
    "youtubeeng" to "youtubeeng",
)