package ca.utoronto.megaapp.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF062452)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF2F4675)
val onPrimaryContainerLight = Color(0xFFD6E0FF)
val secondaryLight = Color(0xFF005165)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF007894)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF006782)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF78D0F3)
val onTertiaryContainerLight = Color(0xFF003A4B)
val errorLight = Color(0xFF9E180C)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFD33F2D)
val onErrorContainerLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFFAF8FD)
val onBackgroundLight = Color(0xFF1A1B1F)
val surfaceLight = Color(0xFFFCF8F8)
val onSurfaceLight = Color(0xFF1C1B1B)
val surfaceVariantLight = Color(0xFFE2E3DB)
val onSurfaceVariantLight = Color(0xFF454742)
val outlineLight = Color(0xFF767871)
val outlineVariantLight = Color(0xFFC6C7BF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313030)
val inverseOnSurfaceLight = Color(0xFFF4F0EF)
val inversePrimaryLight = Color(0xFFAFC6FD)
val surfaceDimLight = Color(0xFFDDD9D9)
val surfaceBrightLight = Color(0xFFFCF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F3F2)
val surfaceContainerLight = Color(0xFFF1EDEC)
val surfaceContainerHighLight = Color(0xFFEBE7E7)
val surfaceContainerHighestLight = Color(0xFFE5E2E1)

val extraLightBlue = Color(0XFFedfbfe)
val lightBlue = Color(0XFFb1ddee)
val roundBookmarkBlue = Color(0xFF2F4675)
val green = Color(0xFF4CAF50)
val red = Color(0xFFF44336)

